#!/bin/bash

DAY=$1
if [[ $DAY -lt 10 ]]; then
  DIR=day0$1
else
  DIR=day$1
fi
YEAR=${2:-2025}

AOC=~/code/advent-of-code
cd "$AOC"
mkdir -p "$YEAR/$DIR"
cd "$YEAR/$DIR"

start_part_2() {
  SANITY="$(cat p2.sh | sha256sum | cut -d' ' -f1)"
  if [[ "$SANITY" == "eebb73afcb24017e3fb49b70786a41e0c2e01fbef4230ae0b75294e93d265205" ]]; then
    echo "Basing p2 on p1 because p2 was blank"
    cp p1.sh p2.sh
  fi
  tmux next-window
  tmux select-pane -t right
  tmux send-keys C-c
  tmux send-keys "~/code/advent-of-code/test-runner $YEAR $DAY 2" Enter
  tmux select-pane -t left
}

touch p1.sh p2.sh
chmod +x p1.sh p2.sh

cat <<-EOF | tee p1.sh > p2.sh
#!/bin/bash

FILE="\$1"

cat "\$FILE"
EOF

if [[ ! -f "input.txt" ]]; then
  curl -Ss "https://adventofcode.com/$YEAR/day/$DAY/input" \
    -H "User-Agent: https://aoc.cgs.dev friendly bash script by s@cgs.dev" \
    -H "cookie: session=$(cat ~/.aoc)" > input.txt
fi

touch p1.sh p2.sh sample1.txt solution1.txt sample2.txt solution2.txt

tmux new-window
tmux send-keys "cd $AOC/$YEAR/$DIR; vim p1.sh p2.sh sample1.txt solution1.txt sample2.txt solution2.txt" Enter
tmux split-window -h
tmux send-keys "cd $AOC/$YEAR/$DIR" Enter
tmux send-keys "$AOC/test-runner $YEAR $DAY 1" Enter

echo
echo
echo ===========================
read -n 1 -s -r -p "Press any key to begin part 2\n"

start_part_2
