#!/usr/bin/env bash

clear
tput civis
declare -A valid
total=0
while IFS= read -r line; do
  valid[$line]=1
  ((total++))
done < hashes


echo
echo
echo "  SYNACOR  OSCON"
echo "  2012 CHALLENGE"
echo "  ============== "
echo
echo -e "  LANG:  BASH"
count=0
while IFS= read -r line; do
  hashed=$(echo -n "$line" | md5sum | cut -d' ' -f1)
  if [[ -n "${valid[$hashed]}" ]]; then
    ((count++))
  elif [[ -z "$invalid" ]]; then
    echo -e "  CODES:\033[31m ERROR\033[0m"
    ((invalid++))
  fi
done < <(sort -u <(cut -d' ' -f1 < codes))

[[ -z "$invalid" ]] && echo -e "  CODES: \033[32m$count / $total\033[0m"
echo
echo
echo
echo -e "\033[35m (pinned in chat)\033[0m"
echo
echo
echo
echo
echo
